projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "https://twatter-backend-e940444166.herokuapp.com"
  prisma:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: prisma.yml
